version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.15 # 官方 etcd 镜像
    container_name: etcd
    ports:
      - "2379:2379"  # 客户端端口
      - "2380:2380"  # 节点间通信端口
    environment:
      - ETCD_NAME=etcd0
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd0=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
    volumes:
      - ./data:/etcd-data  # 数据持久化
    restart: unless-stopped

volumes:
  etcd-data:
