version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - ./data:/data/db             # 数据文件
      - ./conf/mongod.conf:/etc/mongod.conf  # 配置文件
      - ./logs:/var/log/mongodb     # 日志文件
    command: mongod --config /etc/mongod.conf  # 使用自定义配置文件启动
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - mongo-net
volumes:
  mongodb_data:
  
networks:
  mongo-net:
    driver: bridge